export const topSellingProducts = [
  {
    link: "https://www.1mg.com/otc/baidyanath-kamini-vidrawan-ras-keshar-yukta-tablet-otc560948",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/tlfgbykcqbhn5jieozfj.jpg",
    name: "Baidyanath Kamini Vidrawan Ras Keshar Yukta Tablet",
    qty: "bottle of 10 gm Tablet",
    strikePrice: "1698",
    discount: "20% off",
    price: "1358",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-vansaar-isabgol-psyllium-husk-powder-otc371516",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/hb574zgh9ypwmpel9mxz.jpg",
    name: "Baidyanath Vansaar Isabgol Psyllium Husk Powder",
    qty: "box of 200 gm Powder",
    strikePrice: "225",
    discount: "14% off",
    price: "193",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-kesari-kalp-royal-chyawanprash-promotes-vitality-strength-stamina-otc325914",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/wxcyaombrajpkyvcvnrm.jpg",
    name: "Baidyanath Kesari Kalp Royal Chyawanprash Promotes Vitality, Strength & Stamina",
    qty: "jar of 1 kg Paste",
    strikePrice: "740",
    discount: "30% off",
    price: "518",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-kanchnar-guggulu-tablet-otc325867",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/zd02vxwzldjojodryrbk.jpg",
    name: "Baidyanath Kanchnar Guggulu Tablet",
    qty: "bottle of 80 tablets",
    strikePrice: "140",
    discount: "14% off",
    price: "120",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-chyawanprash-special-immunity-booster-for-omniprotection-with-madhu-free-50gm-otc698062",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/r4q79nrsaa1tfaxfvbn7.jpg",
    name: "Baidyanath Chyawanprash Special Immunity Booster for OmniProtection with Madhu Free 50gm",
    qty: "jar of 950 gm Paste",
    strikePrice: "395",
    discount: "15% off",
    price: "336",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-vita-ex-massage-oil-otc349340",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/cropped/yrlsaq5pmpkpmu0u0cqd.jpg",
    name: "Baidyanath Vita EX Massage Oil",
    qty: "bottle of 15 ml Oil",
    strikePrice: "225",
    discount: "15% off",
    price: "191",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-kesari-kalp-royal-chyawanprash-promotes-vitality-strength-stamina-otc388303",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/sotrimm6r6qrtbt5qtmw.jpg",
    name: "Baidyanath Kesari Kalp Royal Chyawanprash Promotes Vitality, Strength & Stamina",
    qty: "jar of 500 gm Paste",
    strikePrice: "420",
    discount: "14% off",
    price: "361",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-chyawan-vit-sugarfree-chyawanprash-for-boosting-immunity-otc337211",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/cropped/crqoyzk9fbxvdpdk2efj.png",
    name: "Baidyanath Chyawan-Vit Sugarfree Chyawanprash for Boosting Immunity",
    qty: "jar of 500 gm Paste",
    strikePrice: "225",
    discount: "15% off",
    price: "191",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-vansaar-aloe-vera-juice-otc349149",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/lc0ysjyol0asm5eeoxut.jpg",
    name: "Baidyanath Vansaar Aloe Vera Juice",
    qty: "bottle of 1 Ltr Juice",
    strikePrice: "265",
    discount: "35% off",
    price: "172",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-vita-ex-gold-capsule-for-vitality-stamina-otc323951",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/ogypzm1jrh5y0gislnwm.jpg",
    name: "Baidyanath Vita-Ex Gold Capsule for Vitality & Stamina",
    qty: "bottle of 20 capsules",
    strikePrice: "475",
    discount: "15% off",
    price: "404",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-vansaar-shilajit-resin-otc671424",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/ttujayukq6mdk95t1aob.jpg",
    name: "Baidyanath Vansaar Shilajit Resin",
    qty: "bottle of 15 gm Pack",
    strikePrice: "1499",
    discount: "15% off",
    price: "1274",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-chitrakadi-bati-tablet-otc327001",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/cropped/zrphzczzrwe4o6hnqmqc.png",
    name: "Baidyanath Chitrakadi Bati Tablet",
    qty: "bottle of 80 tablets",
    strikePrice: "94",
    discount: "14% off",
    price: "81",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-vansaar-isabgol-psyllium-husk-powder-otc497819",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/dxxwizplopbwahvbcbb2.jpg",
    name: "Baidyanath Vansaar Isabgol Psyllium Husk Powder",
    qty: "box of 100 gm Powder",
    strikePrice: "120",
    discount: "15% off",
    price: "102",
  },
  {
    link: "https://www.1mg.com/otc/baidyanath-vansaar-triphala-juice-natural-herbal-laxative-otc349184",
    img: "https://onemg.gumlet.io/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/foeocdhjfl51ub5wafmg.jpg",
    name: "Baidyanath Vansaar Triphala Juice Natural Herbal Laxative",
    qty: "bottle of 1 Ltr Juice",
    strikePrice: "265",
    discount: "13% off",
    price: "230",
  },
];
